### PR TITLE
Added ui_method

### PR DESCRIPTION
**Pull request by kwarunek**
More elegant way to make xstatic helper available in template.

### CODE REVIEW

**Comment by takluyver** [comment]
Oh, neat, I didn't know about that. I'd like to think of a clearer name for it, though - I'll think for a bit and let you know what I come up with.

In most projects I work on, I'd ask you to remake these changes without all the code reformatting - but this repo is quiet enough that it doesn't really matter.

**Comment by kwarunek** [comment]
No problem. About reformatting I'm feeling like you, but I have been tempted by flake8 and the reason that there is one file and small changes... ;)

**Comment by takluyver** [comment]
How about calling it `xstatic_url`, and adding a docstring explaining what it is?

**Comment by kwarunek** [comment]
I've made proposed changes :)

**Comment by takluyver** [comment]
Thanks!

**Comment by kwarunek** [comment]
Thanks! It would be great if you could publish upgrade to pypi. TIA

**Comment by takluyver** [comment]
Here you go: https://pypi.python.org/pypi/tornado_xstatic

**Comment by kwarunek** [comment]
Thank you very much.

**Pull request merged**
